---
title: "Vessel Tracks + Whale Sightings"
author: "WorthWhale Team"
date: "10/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
#load packages
library(tidyverse)
library(lubridate)

```

```{r}

# Read in vessel track data for April 20, 2017
vesseltracks <- read.csv("data/GPXtoCSV04-20.csv")

# Read in whale sightings data for April 20, 2017
whaleclusters <- read.csv("data/2017_clusters_04-20.csv")
# if we do a read_csv, we can specify how the indiv columns are translated
  # look in Hadley book for how this works
  # when googling, include "tidyverse" not even "R"



```

THIS IS THE EXAMPLE CODE TO COPY FOR EACH YEAR

```{r}

vesseltracks$GPStime <- parse_date_time(vesseltracks$time, "%Y/%m/%d %H:%M:%S", tz = "America/Dominica")
# Match the date you have in your data, R will spit out the correct date format. For Dominica, you have to set the time zone, otherwise R assumes UTC format

whaleclusters$GPStime <- parse_date_time(whaleclusters$DateTime, "%d/%m/%Y %H:%M:%S", tz = "America/Dominica")
    # Change the "DateTime" column name to "GPStime" in whaleclusters_0420_2017

#Create function to get whale cluster time to equal the GPS time in order to connect vessel track lat long to whale cluster lat long
#Subtract the whale cluster gps time and the vessel tracks gps time 
#find the absolute value 
#take the min value of the absolute value
#
#apply the fuction to all rows in the whalecluster df
closest <- sapply(seq(nrow(whaleclusters)), function(i) {which.min(abs(whaleclusters$GPStime[i] - vesseltracks$GPStime))})

whaleclusters$Lat <- vesseltracks$lat[closest]

whaleclusters$Long <- vesseltracks$lon[closest]

```

Create this same chunk for each year. The Whale Cluster data from 2005-2015 already have lat/lon. so only use the vessel tracks data from 2016-2018

```{r}
#2016

#read in 2016 vessel tracks csv

vesseltracks2016 <- read.csv("2016.csv")

#read in 2016 whale clusters
whaleclusters2016 <- read.csv("Whale_Clusters/2016_cluster.csv")


vesseltracks2016$GPStime <- parse_date_time(vesseltracks2016$time, "%Y/%m/%d %H:%M:%S", tz = "America/Dominica")
# Match the date you have in your data, R will spit out the correct date format. For Dominica, you have to set the time zone, otherwise R assumes UTC format

whaleclusters2016$GPStime <- parse_date_time(whaleclusters2016$DateTime, "%d/%m/%y %H:%M:%S", tz = "America/Dominica")
    # Change the "DateTime" column name to "GPStime" in 2016 whale clusters: change Y to y because the year is in two digit format, not four. 
#
#Create function to get whale cluster time to equal the GPS time in order to connect vessel track lat long to whale cluster lat long
#Subtract the whale cluster gps time and the vessel tracks gps time 
#find the absolute value 
#take the min value of the absolute value
#
#apply the fuction to all rows in the whalecluster df
closest2016 <- sapply(seq(nrow(whaleclusters2016)), function(i) {which.min(abs(whaleclusters2016$GPStime[i] - vesseltracks2016$GPStime))})

whaleclusters2016$Lat <- vesseltracks2016$lat[closest2016]

whaleclusters2016$Long <- vesseltracks2016$lon[closest2016]


```

```{r}
#2017

#read in 2017 vessel tracks csv
vesseltracks2017 <- read.csv("2017.csv")

#read in 2016 whale clusters
whaleclusters2017 <- read.csv("Whale_Clusters/2017_cluster.csv")


vesseltracks2017$GPStime <- parse_date_time(vesseltracks2017$time, "%Y/%m/%d %H:%M:%S", tz = "America/Dominica")
# Match the date you have in your data, R will spit out the correct date format. For Dominica, you have to set the time zone, otherwise R assumes UTC format

whaleclusters2017$GPStime <- parse_date_time(whaleclusters2017$DateTime, "%d/%m/%y %H:%M:%S", tz = "America/Dominica")
    # Change the "DateTime" column name to "GPStime" in 2016 whale clusters: change Y to y because the year is in two digit format, not four. 
#
#Create function to get whale cluster time to equal the GPS time in order to connect vessel track lat long to whale cluster lat long
#Subtract the whale cluster gps time and the vessel tracks gps time 
#find the absolute value 
#take the min value of the absolute value
#
#apply the fuction to all rows in the whalecluster df
closest2017 <- sapply(seq(nrow(whaleclusters2017)), function(i) {which.min(abs(whaleclusters2017$GPStime[i] - vesseltracks2017$GPStime))})

whaleclusters2017$Lat <- vesseltracks2017$lat[closest2017]

whaleclusters2017$Long <- vesseltracks2017$lon[closest2017]




```

```{r}
#2018

#read in 2017 vessel tracks csv
vesseltracks2018 <- read.csv("2018.csv")


#read in 2016 whale clusters
whaleclusters2018 <- read.csv("Whale_Clusters/2018_cluster.csv")


vesseltracks2018$GPStime <- parse_date_time(vesseltracks2018$time, "%b/%d/%Y %H:%M:%S", tz = "America/Dominica")
# Match the date you have in your data, R will spit out the correct date format. For Dominica, you have to set the time zone, otherwise R assumes UTC format

whaleclusters2018$GPStime <- parse_date_time(whaleclusters2018$DateTime, "%d/%m/%y %H:%M:%S", tz = "America/Dominica")
    # Change the "DateTime" column name to "GPStime" in 2016 whale clusters: change Y to y because the year is in two digit format, not four. 
#
#Create function to get whale cluster time to equal the GPS time in order to connect vessel track lat long to whale cluster lat long
#Subtract the whale cluster gps time and the vessel tracks gps time 
#find the absolute value 
#take the min value of the absolute value
#
#apply the fuction to all rows in the whalecluster df
closest2018 <- sapply(seq(nrow(whaleclusters2018)), function(i) {which.min(abs(whaleclusters2018$GPStime[i] - vesseltracks2018$GPStime))})

whaleclusters2018$Lat <- vesseltracks2018$lat[closest2018]

whaleclusters2017$Long <- vesseltracks2017$lon[closest2017]



```


